services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-dejf-10c
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  frontend:
    image: client:v1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8080
        API_BASE: /api/usuarios
        API_PROTOCOL: https
    container_name: sgu-frontend
    ports:
      - "3000:443"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - database

  backend:
    image: server:v1.0-sgu
    container_name: sgu-backend
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-dejf-10c
      DB_USER: root
      DB_PASS: root
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEYSTORE: /etc/letsencrypt/live/localhost/keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: changeit
    ports:
      - "8080:8080"
    networks:
      - sgu-net
    volumes:
      - certbot-conf:/etc/letsencrypt:ro
    depends_on:
      - frontend

networks:
  sgu-net:
    external: true


volumes:
  sgu-volume:
    external: true
  certbot-conf:
    external: true
      